"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { jsPDF } from "jspdf";
import { getAllPrintables, PrintableItem, CDN_BASE_URL } from "@/lib/printables-data";
import { Download, Printer, Star, ChevronDown, Palette, ArrowRight, CheckCircle2, Loader2, Sparkles } from "lucide-react";

function getColoringPrintables(): PrintableItem[] {
    const all = getAllPrintables();
    // Select a mix of easy and medium items that work well as coloring pages
    const easy = all.filter(item => item.difficulty === "Easy");
    const medium = all.filter(item => item.difficulty === "Medium");
    return [...easy, ...medium].slice(0, 12);
}

function loadCrossOriginImage(url: string): Promise<HTMLImageElement> {
    return new Promise((resolve, reject) => {
        const img = new window.Image();
        img.crossOrigin = "Anonymous";
        const timestamp = new Date().getTime();
        img.src = `${url}${url.includes('?') ? '&' : '?'}t=${timestamp}`;
        img.onload = () => resolve(img);
        img.onerror = reject;
    });
}

function addImageToPdf(doc: jsPDF, img: HTMLImageElement, isFirstPage: boolean) {
    if (!isFirstPage) doc.addPage();

    const canvas = document.createElement('canvas');
    canvas.width = img.width;
    canvas.height = img.height;
    const ctx = canvas.getContext('2d')!;
    ctx.fillStyle = "#FFFFFF";
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(img, 0, 0);

    const imgData = canvas.toDataURL('image/jpeg', 0.95);
    const { width: pageWidth, height: pageHeight } = doc.internal.pageSize;
    const margin = 10;
    const imgRatio = img.width / img.height;
    let finalWidth = pageWidth - margin * 2;
    let finalHeight = finalWidth / imgRatio;

    if (finalHeight > pageHeight - margin * 2) {
        finalHeight = pageHeight - margin * 2;
        finalWidth = finalHeight * imgRatio;
    }

    const x = (pageWidth - finalWidth) / 2;
    const y = (pageHeight - finalHeight) / 2;
    doc.addImage(imgData, 'JPEG', x, y, finalWidth, finalHeight);
}

async function handleDownloadPdf(item: PrintableItem, setDownloading: (v: boolean) => void) {
    setDownloading(true);
    try {
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
        const { width: pageWidth, height: pageHeight } = doc.internal.pageSize;

        // Page 1: Puzzle (connect the dots)
        const puzzleImg = await loadCrossOriginImage(item.imageUrl);
        addImageToPdf(doc, puzzleImg, true);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Page 1: Connect the Dots Puzzle", pageWidth / 2, pageHeight - 5, { align: "center" });

        // Page 2: Solution (outline for coloring)
        const solutionImg = await loadCrossOriginImage(item.solutionUrl);
        addImageToPdf(doc, solutionImg, false);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Page 2: Color This Picture!", pageWidth / 2, pageHeight - 5, { align: "center" });

        // Page 3: Colored example (if available)
        if (item.coloredImageUrl) {
            try {
                const coloredImg = await loadCrossOriginImage(item.coloredImageUrl);
                addImageToPdf(doc, coloredImg, false);
                doc.setFontSize(8);
                doc.setTextColor(150);
                doc.text("Page 3: Example - What It Can Look Like", pageWidth / 2, pageHeight - 5, { align: "center" });
            } catch {
                // Colored image not available, skip silently
            }
        }

        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Generated by ConnectTheDotsPrintable.online", pageWidth / 2, pageHeight - 2, { align: "center" });

        const cleanTitle = item.title.replace(/[^a-zA-Z0-9]/g, '_');
        doc.save(`${cleanTitle}_Coloring_Pages.pdf`);
    } catch (error) {
        console.error("PDF download failed:", error);
        alert("Failed to generate PDF. Please try again.");
    } finally {
        setDownloading(false);
    }
}

function PrintableCard({ item }: { item: PrintableItem }) {
    const [downloading, setDownloading] = useState(false);
    const [showColored, setShowColored] = useState(false);
    const dotLabel = Array.isArray(item.dotRange)
        ? `${item.dotRange[0]}-${item.dotRange[1]}`
        : item.dotRange;

    const hasColored = !!item.coloredImageUrl;
    const currentImage = showColored && hasColored ? item.coloredImageUrl! : item.solutionUrl;
    const currentAlt = showColored && hasColored ? `${item.title} colored example` : item.solutionAltText;

    return (
        <div className="group bg-white rounded-xl border border-gray-100 shadow-sm hover:shadow-lg transition-all duration-300 overflow-hidden">
            <Link href={item.detailPage} className="block">
                <div
                    className="relative aspect-square bg-gray-50 overflow-hidden"
                    onMouseEnter={() => hasColored && setShowColored(true)}
                    onMouseLeave={() => hasColored && setShowColored(false)}
                >
                    {/* Solution outline (default) */}
                    <Image
                        src={currentImage}
                        alt={currentAlt}
                        fill
                        sizes="(max-width: 640px) 50vw, (max-width: 1024px) 33vw, 25vw"
                        className="object-contain p-4 transition-all duration-500"
                        loading="lazy"
                    />
                    {/* Colored badge on hover */}
                    {hasColored && showColored && (
                        <span className="absolute top-2 right-2 bg-green-500 text-white text-[10px] font-bold px-2 py-0.5 rounded-full shadow z-10 animate-pulse">
                            Colored
                        </span>
                    )}
                </div>
            </Link>
            <div className="p-3">
                <h3 className="font-semibold text-gray-800 text-sm truncate">{item.title}</h3>
                <div className="flex items-center gap-2 mt-1">
                    <span className="text-xs bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full font-medium">
                        {dotLabel} dots
                    </span>
                    <span className="text-xs text-gray-500">{item.ageRecommendation}</span>
                </div>
                {/* Mobile toggle button for colored/uncolored */}
                {hasColored && (
                    <button
                        onClick={(e) => {
                            e.preventDefault();
                            e.stopPropagation();
                            setShowColored(!showColored);
                        }}
                        className="mt-2 w-full flex items-center justify-center gap-1.5 bg-gray-100 hover:bg-gray-200 text-gray-700 text-xs font-medium py-1.5 px-3 rounded-lg transition-colors md:hidden"
                    >
                        <Palette size={12} />
                        {showColored ? "Show Outline" : "Show Colored"}
                    </button>
                )}
                <button
                    onClick={(e) => {
                        e.stopPropagation();
                        handleDownloadPdf(item, setDownloading);
                    }}
                    disabled={downloading}
                    className="mt-2 w-full flex items-center justify-center gap-1.5 bg-purple-600 hover:bg-purple-700 text-white text-xs font-medium py-2 px-3 rounded-lg transition-colors disabled:opacity-70 disabled:cursor-wait"
                >
                    {downloading ? (
                        <>
                            <Loader2 size={14} className="animate-spin" />
                            Generating PDF...
                        </>
                    ) : (
                        <>
                            <Download size={14} />
                            Download PDF
                        </>
                    )}
                </button>
            </div>
        </div>
    );
}

function FAQItem({ question, answer }: {
    question: string;
    answer: string;
}) {
    return (
        <div className="border border-gray-200 rounded-lg overflow-hidden">
            <div className="w-full p-4 text-left">
                <span className="font-semibold text-gray-800">{question}</span>
            </div>
            <div className="px-4 pb-4 text-gray-600 leading-relaxed border-t border-gray-100 pt-3">
                {answer}
            </div>
        </div>
    );
}

// Demo comparison data for the showcase section
const DEMO_COMPARISONS = [
    {
        id: "cute-kitten",
        title: "Cute Kitten",
        outlineUrl: "/colorpage/kitten_lineart.png",
        coloredUrl: "/colorpage/kitten_color.png",
    },
    {
        id: "baby-dinosaur",
        title: "Baby Dinosaur",
        outlineUrl: "/colorpage/dinosaur_lineart.png",
        coloredUrl: "/colorpage/dinosaur_color.png",
    },
    {
        id: "butterfly",
        title: "Butterfly",
        outlineUrl: "/colorpage/butterfly_lineart.png",
        coloredUrl: "/colorpage/butterfly_color.png",
    },
    {
        id: "puppy",
        title: "Puppy",
        outlineUrl: "/colorpage/puppy_lineart.png",
        coloredUrl: "/colorpage/puppy_color.png",
    },
    {
        id: "bunny",
        title: "Bunny",
        outlineUrl: "/colorpage/bunny_lineart.png",
        coloredUrl: "/colorpage/bunny_color.png",
    },
];

function loadLocalImage(url: string): Promise<HTMLImageElement> {
    return new Promise((resolve, reject) => {
        const img = new window.Image();
        img.src = url;
        img.onload = () => resolve(img);
        img.onerror = reject;
    });
}

function addLocalImageToPdf(doc: jsPDF, img: HTMLImageElement, isFirstPage: boolean) {
    if (!isFirstPage) doc.addPage();

    const canvas = document.createElement('canvas');
    canvas.width = img.width;
    canvas.height = img.height;
    const ctx = canvas.getContext('2d')!;
    ctx.fillStyle = "#FFFFFF";
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(img, 0, 0);

    const imgData = canvas.toDataURL('image/png', 1.0);
    const { width: pageWidth, height: pageHeight } = doc.internal.pageSize;
    const margin = 10;
    const imgRatio = img.width / img.height;
    let finalWidth = pageWidth - margin * 2;
    let finalHeight = finalWidth / imgRatio;

    if (finalHeight > pageHeight - margin * 2) {
        finalHeight = pageHeight - margin * 2;
        finalWidth = finalHeight * imgRatio;
    }

    const x = (pageWidth - finalWidth) / 2;
    const y = (pageHeight - finalHeight) / 2;
    doc.addImage(imgData, 'PNG', x, y, finalWidth, finalHeight);
}

async function handleDownloadComparisonPdf(
    item: typeof DEMO_COMPARISONS[number],
    setDownloading: (v: boolean) => void
) {
    setDownloading(true);
    try {
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
        const { width: pageWidth, height: pageHeight } = doc.internal.pageSize;

        // Page 1: Line art (for coloring)
        const outlineImg = await loadLocalImage(item.outlineUrl);
        addLocalImageToPdf(doc, outlineImg, true);
        doc.setFontSize(12);
        doc.setTextColor(100);
        doc.text(`${item.title} - Connect the Dots & Color!`, pageWidth / 2, 8, { align: "center" });
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Page 1: Connect the dots, then color this picture!", pageWidth / 2, pageHeight - 5, { align: "center" });

        // Page 2: Colored reference
        const coloredImg = await loadLocalImage(item.coloredUrl);
        addLocalImageToPdf(doc, coloredImg, false);
        doc.setFontSize(12);
        doc.setTextColor(100);
        doc.text(`${item.title} - Color Reference`, pageWidth / 2, 8, { align: "center" });
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Page 2: Example - What it can look like when colored!", pageWidth / 2, pageHeight - 5, { align: "center" });

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Generated by ConnectTheDotsPrintable.online", pageWidth / 2, pageHeight - 2, { align: "center" });

        const cleanTitle = item.title.replace(/[^a-zA-Z0-9]/g, '_');
        doc.save(`${cleanTitle}_Coloring_Page.pdf`);
    } catch (error) {
        console.error("PDF download failed:", error);
        alert("Failed to generate PDF. Please try again.");
    } finally {
        setDownloading(false);
    }
}

function ComparisonCard({ item }: { item: typeof DEMO_COMPARISONS[number] }) {
    const [downloading, setDownloading] = useState(false);

    return (
        <div className="group bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-lg transition-all duration-300 hover:-translate-y-1">
            <div className="p-3 pb-3">
                <h3 className="text-sm font-bold text-gray-800 text-center mb-3">{item.title}</h3>

                {/* Outline Image */}
                <div className="relative rounded-xl overflow-hidden bg-gray-50 mb-2">
                    <div className="aspect-square relative">
                        <Image
                            src={item.outlineUrl}
                            alt={`${item.title} outline`}
                            fill
                            sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 20vw"
                            className="object-contain p-3"
                            loading="lazy"
                        />
                    </div>
                    <span className="absolute bottom-1.5 left-1.5 bg-gray-800/80 text-white text-[10px] font-bold px-2 py-0.5 rounded-full backdrop-blur-sm">
                        Step 1: Outline
                    </span>
                </div>

                {/* Arrow */}
                <div className="flex justify-center my-1">
                    <div className="w-8 h-8 rounded-full bg-purple-100 flex items-center justify-center group-hover:bg-purple-200 transition-colors">
                        <ArrowRight size={14} className="text-purple-600 rotate-90" />
                    </div>
                </div>

                {/* Colored Image */}
                <div className="relative rounded-xl overflow-hidden bg-gray-50 mb-3">
                    <div className="aspect-square relative">
                        <Image
                            src={item.coloredUrl}
                            alt={`${item.title} colored`}
                            fill
                            sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 20vw"
                            className="object-contain p-3"
                            loading="lazy"
                        />
                    </div>
                    <span className="absolute bottom-1.5 left-1.5 bg-green-600/90 text-white text-[10px] font-bold px-2 py-0.5 rounded-full backdrop-blur-sm">
                        Step 2: Colored
                    </span>
                </div>

                {/* Download Button */}
                <button
                    onClick={() => handleDownloadComparisonPdf(item, setDownloading)}
                    disabled={downloading}
                    className="w-full flex items-center justify-center gap-1.5 bg-purple-600 hover:bg-purple-700 text-white text-xs font-medium py-2 px-3 rounded-lg transition-colors disabled:opacity-70 disabled:cursor-wait"
                >
                    {downloading ? (
                        <>
                            <Loader2 size={14} className="animate-spin" />
                            Generating...
                        </>
                    ) : (
                        <>
                            <Download size={14} />
                            Download PDF
                        </>
                    )}
                </button>
            </div>
        </div>
    );
}

function ComparisonShowcase() {
    return (
        <section className="mb-16">
            <div className="text-center mb-8">
                <div className="inline-flex items-center gap-2 bg-purple-100 text-purple-700 text-sm font-semibold px-4 py-1.5 rounded-full mb-4">
                    <Sparkles size={14} />
                    See the Magic
                </div>
                <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-3">
                    Connect the Dots → <span className="text-purple-600">Color It In!</span>
                </h2>
                <p className="text-gray-600 max-w-xl mx-auto">
                    See how a simple outline transforms into a colorful masterpiece. Each page gives your child two activities in one!
                </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
                {DEMO_COMPARISONS.map((item) => (
                    <ComparisonCard key={item.id} item={item} />
                ))}
            </div>
        </section>
    );
}

export default function ColoringPagesContent() {
    const printables = getColoringPrintables();
    const [showAll, setShowAll] = useState(false);

    const displayedPrintables = showAll ? printables : printables.slice(0, 8);

    const faqItems = [
        {
            q: "What are connect the dots coloring pages?",
            a: "Connect the dots coloring pages are printable worksheets that combine two activities in one: first, children connect numbered dots to reveal a hidden picture, then they color it in. This dual activity keeps kids engaged longer and develops both number recognition and creative expression skills."
        },
        {
            q: "What age are dot to dot coloring pages suitable for?",
            a: "Connect the dots coloring pages are suitable for children ages 3-10. Younger children (3-5) can start with simple 1-20 dot pages, while older kids (6-10) enjoy more complex designs with 50-100+ dots. The coloring step adds an extra creative layer that appeals to a wide age range."
        },
        {
            q: "How do I download and print these coloring pages?",
            a: "Click the Download PDF button on any coloring page. Open the PDF file and select Print. Choose 'Fit to Page' for best results. We recommend standard A4 or Letter size paper. For coloring, regular copy paper works fine, or use cardstock for markers and paint."
        },
        {
            q: "What is the difference between coloring pages and connect the dots pages?",
            a: "Traditional coloring pages show a pre-drawn outline for children to color. Connect the dots pages require children to draw the outline by connecting numbered dots first. Our connect the dots coloring pages combine both: connect the dots to reveal the image, then color it in for a complete two-step activity."
        },
        {
            q: "Are these connect the dots coloring pages really free?",
            a: "Yes! All our connect the dots coloring pages are completely free to download and print. No sign-up, no payment, no watermarks. They are for personal and educational use only."
        }
    ];

    return (
        <main className="bg-slate-50 min-h-screen">
            {/* Breadcrumb */}
            <nav className="container mx-auto max-w-6xl px-4 pt-6 pb-2" aria-label="Breadcrumb">
                <ol className="flex items-center gap-2 text-sm text-gray-500">
                    <li><Link href="/" className="hover:text-purple-600 transition-colors">Home</Link></li>
                    <li className="text-gray-300">/</li>
                    <li className="text-gray-800 font-medium">Connect the Dots Coloring Pages</li>
                </ol>
            </nav>

            <div className="container mx-auto max-w-6xl px-4 py-8">
                {/* Hero Section */}
                <header className="text-center mb-12">
                    <h1 className="text-3xl md:text-4xl lg:text-5xl font-extrabold text-gray-900 mb-4 leading-tight">
                        Free <span className="text-purple-600">Connect the Dots Coloring Pages</span>
                    </h1>
                    <p className="text-lg text-gray-600 max-w-2xl mx-auto leading-relaxed">
                        Download 20+ free dot to dot coloring pages that combine puzzle-solving with creative coloring.
                        Connect the numbered dots, reveal the hidden picture, then bring it to life with colors!
                    </p>
                    <div className="flex items-center justify-center gap-4 mt-6 text-sm text-gray-500">
                        <span className="flex items-center gap-1"><Star size={16} className="text-yellow-500" /> 20+ Free Pages</span>
                        <span className="flex items-center gap-1"><Printer size={16} /> Instant PDF Download</span>
                        <span className="flex items-center gap-1"><Palette size={16} /> Connect & Color</span>
                    </div>
                    <p className="text-xs text-gray-400 mt-3">Last updated July 14, 2026</p>
                </header>

                {/* Comparison Showcase */}
                <ComparisonShowcase />

                {/* Compact generator CTA — earlier in the page than the bottom-of-page one */}
                <div className="mb-16 flex flex-col sm:flex-row items-center justify-between gap-4 bg-purple-50 border border-purple-100 rounded-2xl px-6 py-5">
                    <p className="text-sm text-gray-700">
                        <span className="font-semibold text-purple-700">Want a design not on this page?</span>{" "}
                        Turn any photo into a custom connect-the-dots coloring page in seconds.
                    </p>
                    <Link
                        href="/"
                        className="shrink-0 inline-flex items-center gap-1.5 px-5 py-2.5 bg-purple-600 hover:bg-purple-700 text-white text-sm font-semibold rounded-full transition-colors"
                    >
                        Try the Free Generator
                        <ArrowRight size={14} />
                    </Link>
                </div>

                {/* Printable Grid */}
                <section className="mb-16">
                    <h2 className="text-2xl font-bold text-gray-900 mb-2">
                        Download Free Connect the Dots Coloring Pages
                    </h2>
                    <p className="text-gray-600 mb-6">
                        Each page is a two-in-one activity: connect the dots to reveal the picture, then color it in. All printables are free with no watermarks.
                    </p>

                    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 md:gap-6">
                        {displayedPrintables.map((item) => (
                            <PrintableCard key={item.id} item={item} />
                        ))}
                    </div>

                    {printables.length > 8 && (
                        <div className="text-center mt-8">
                            <button
                                onClick={() => setShowAll(!showAll)}
                                className="inline-flex items-center gap-2 px-6 py-3 bg-white border-2 border-purple-600 text-purple-600 font-semibold rounded-full hover:bg-purple-50 transition-colors"
                            >
                                {showAll ? "Show Less" : `Load More (${printables.length - 8} more)`}
                                <ChevronDown size={18} className={`transition-transform ${showAll ? "rotate-180" : ""}`} />
                            </button>
                        </div>
                    )}
                </section>

                {/* What Makes These Special */}
                <section className="mb-16 bg-white rounded-2xl p-8 shadow-sm">
                    <div className="flex items-center gap-3 mb-4">
                        <Palette size={28} className="text-purple-600" />
                        <h2 className="text-2xl font-bold text-gray-900">Why Connect the Dots + Coloring?</h2>
                    </div>
                    <div className="grid md:grid-cols-2 gap-8">
                        <div>
                            <p className="text-gray-600 leading-relaxed mb-4">
                                Connect the dots coloring pages offer a unique two-step activity that keeps children
                                engaged far longer than a standard worksheet. First, kids practice
                                <strong className="text-gray-800"> number sequencing</strong> and
                                <strong className="text-gray-800"> fine motor control</strong> as they draw lines
                                between dots. Then, they switch to creative mode and color in the revealed image.
                            </p>
                            <p className="text-gray-600 leading-relaxed">
                                This combination of structured problem-solving followed by open-ended creativity
                                makes these pages ideal for both classroom activities and quiet time at home.
                            </p>
                            <p className="text-xs text-gray-400 mt-4">
                                Source:{" "}
                                <a
                                    href="https://research.aota.org/ajot/article/78/3/7803205080/25181/Quantifying-Coloring-Skills-Among-Preschoolers"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-purple-600 hover:underline"
                                >
                                    American Journal of Occupational Therapy — coloring skills in preschoolers
                                </a>
                            </p>
                        </div>
                        <div className="bg-purple-50 rounded-xl p-6">
                            <h3 className="font-semibold text-gray-800 mb-3">Benefits of Two-in-One Activities:</h3>
                            <ul className="space-y-3">
                                <li className="flex items-start gap-2">
                                    <CheckCircle2 size={18} className="text-purple-600 shrink-0 mt-0.5" />
                                    <span className="text-gray-700"><strong>Longer Engagement:</strong> Two activities mean kids stay focused twice as long</span>
                                </li>
                                <li className="flex items-start gap-2">
                                    <CheckCircle2 size={18} className="text-purple-600 shrink-0 mt-0.5" />
                                    <span className="text-gray-700"><strong>Number Skills:</strong> Connecting dots reinforces counting and sequencing</span>
                                </li>
                                <li className="flex items-start gap-2">
                                    <CheckCircle2 size={18} className="text-purple-600 shrink-0 mt-0.5" />
                                    <span className="text-gray-700"><strong>Creative Expression:</strong> Coloring lets kids personalize each finished puzzle</span>
                                </li>
                                <li className="flex items-start gap-2">
                                    <CheckCircle2 size={18} className="text-purple-600 shrink-0 mt-0.5" />
                                    <span className="text-gray-700"><strong>Confidence Building:</strong> Revealing a hidden picture feels like an achievement</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </section>

                {/* Comparison: Coloring vs Connect the Dots */}
                <section className="mb-16">
                    <h2 className="text-2xl font-bold text-gray-900 mb-6">Coloring Pages vs Connect the Dots</h2>
                    <div className="grid md:grid-cols-3 gap-6">
                        <div className="bg-white rounded-xl p-6 shadow-sm border-t-4 border-gray-300">
                            <h3 className="font-semibold text-gray-800 mb-3 text-center">Coloring Pages</h3>
                            <ul className="space-y-2 text-sm text-gray-600">
                                <li className="flex items-start gap-2">
                                    <span className="text-gray-400 shrink-0">-</span>
                                    Pre-drawn outlines ready to color
                                </li>
                                <li className="flex items-start gap-2">
                                    <span className="text-gray-400 shrink-0">-</span>
                                    Focus on color choice and creativity
                                </li>
                                <li className="flex items-start gap-2">
                                    <span className="text-gray-400 shrink-0">-</span>
                                    No puzzle-solving element
                                </li>
                            </ul>
                        </div>
                        <div className="bg-white rounded-xl p-6 shadow-sm border-t-4 border-purple-500 ring-2 ring-purple-200">
                            <h3 className="font-semibold text-purple-700 mb-3 text-center">Connect the Dots + Coloring</h3>
                            <ul className="space-y-2 text-sm text-gray-600">
                                <li className="flex items-start gap-2">
                                    <CheckCircle2 size={14} className="text-purple-500 shrink-0 mt-0.5" />
                                    Number sequencing + coloring in one
                                </li>
                                <li className="flex items-start gap-2">
                                    <CheckCircle2 size={14} className="text-purple-500 shrink-0 mt-0.5" />
                                    Puzzle reveals hidden picture first
                                </li>
                                <li className="flex items-start gap-2">
                                    <CheckCircle2 size={14} className="text-purple-500 shrink-0 mt-0.5" />
                                    Two activities = double the engagement
                                </li>
                            </ul>
                        </div>
                        <div className="bg-white rounded-xl p-6 shadow-sm border-t-4 border-gray-300">
                            <h3 className="font-semibold text-gray-800 mb-3 text-center">Connect the Dots Only</h3>
                            <ul className="space-y-2 text-sm text-gray-600">
                                <li className="flex items-start gap-2">
                                    <span className="text-gray-400 shrink-0">-</span>
                                    Line drawing only, no coloring
                                </li>
                                <li className="flex items-start gap-2">
                                    <span className="text-gray-400 shrink-0">-</span>
                                    Great for number practice
                                </li>
                                <li className="flex items-start gap-2">
                                    <span className="text-gray-400 shrink-0">-</span>
                                    Less creative expression
                                </li>
                            </ul>
                        </div>
                    </div>
                </section>

                {/* How to Use */}
                <section className="mb-16">
                    <h2 className="text-2xl font-bold text-gray-900 mb-6">How to Use These Coloring Pages</h2>
                    <div className="grid md:grid-cols-3 gap-6">
                        <div className="bg-white rounded-xl p-6 text-center shadow-sm">
                            <div className="w-12 h-12 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center mx-auto mb-4 text-xl font-bold">1</div>
                            <h3 className="font-semibold text-gray-800 mb-2">Choose a Design</h3>
                            <p className="text-sm text-gray-600">Browse the collection above and pick a design your child will love — animals, vehicles, or nature themes.</p>
                        </div>
                        <div className="bg-white rounded-xl p-6 text-center shadow-sm">
                            <div className="w-12 h-12 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center mx-auto mb-4 text-xl font-bold">2</div>
                            <h3 className="font-semibold text-gray-800 mb-2">Connect the Dots</h3>
                            <p className="text-sm text-gray-600">Print the page. Have your child connect the numbered dots in order using a pencil or crayon to reveal the hidden picture.</p>
                        </div>
                        <div className="bg-white rounded-xl p-6 text-center shadow-sm">
                            <div className="w-12 h-12 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center mx-auto mb-4 text-xl font-bold">3</div>
                            <h3 className="font-semibold text-gray-800 mb-2">Color It In!</h3>
                            <p className="text-sm text-gray-600">Once the picture is revealed, grab crayons, markers, or colored pencils and bring the artwork to life with color!</p>
                        </div>
                    </div>
                </section>

                {/* Internal Links Section */}
                <section className="mb-16 bg-gradient-to-br from-purple-50 to-indigo-50 rounded-2xl p-8">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">Explore More Printables</h2>
                    <p className="text-gray-600 mb-6">
                        Looking for more activities? We have a huge collection of dot to dot printables for every age and interest.
                    </p>
                    <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
                        <Link href="/printable-connect-the-dots/" className="bg-white rounded-xl p-4 hover:shadow-md transition-shadow group">
                            <h3 className="font-semibold text-purple-600 group-hover:underline">All Printable Connect the Dots</h3>
                            <p className="text-sm text-gray-600 mt-1">Browse our full collection — easy, medium, hard, and extreme worksheets.</p>
                        </Link>
                        <Link href="/free-animal-dot-to-dot-printables-pdf/" className="bg-white rounded-xl p-4 hover:shadow-md transition-shadow group">
                            <h3 className="font-semibold text-purple-600 group-hover:underline">Animal Dot to Dot Printables</h3>
                            <p className="text-sm text-gray-600 mt-1">Animal-themed worksheets that kids love — dogs, cats, dinosaurs, and more.</p>
                        </Link>
                        <Link href="/connect-the-dots-1-to-10/" className="bg-white rounded-xl p-4 hover:shadow-md transition-shadow group">
                            <h3 className="font-semibold text-purple-600 group-hover:underline">Connect the Dots 1 to 10</h3>
                            <p className="text-sm text-gray-600 mt-1">Easy worksheets for toddlers and preschoolers learning to count.</p>
                        </Link>
                        <Link href="/christmas-printables/" className="bg-white rounded-xl p-4 hover:shadow-md transition-shadow group">
                            <h3 className="font-semibold text-purple-600 group-hover:underline">Christmas Printables</h3>
                            <p className="text-sm text-gray-600 mt-1">Festive holiday-themed connect the dots for seasonal fun.</p>
                        </Link>
                        <Link href="/how-to-make/" className="bg-white rounded-xl p-4 hover:shadow-md transition-shadow group">
                            <h3 className="font-semibold text-purple-600 group-hover:underline">How to Make Dot to Dot</h3>
                            <p className="text-sm text-gray-600 mt-1">Learn how to create your own custom connect the dots puzzles.</p>
                        </Link>
                        <Link href="/" className="bg-white rounded-xl p-4 hover:shadow-md transition-shadow group">
                            <h3 className="font-semibold text-purple-600 group-hover:underline">AI Dot to Dot Generator</h3>
                            <p className="text-sm text-gray-600 mt-1">Create custom puzzles from any image with our free online tool.</p>
                        </Link>
                    </div>
                </section>

                {/* FAQ */}
                <section className="mb-16">
                    <h2 className="text-2xl font-bold text-gray-900 mb-6">Frequently Asked Questions</h2>
                    <div className="space-y-3 max-w-3xl">
                        {faqItems.map((item, index) => (
                            <FAQItem
                                key={index}
                                question={item.q}
                                answer={item.a}
                            />
                        ))}
                    </div>
                </section>

                {/* Bottom CTA */}
                <section className="text-center bg-purple-600 text-white rounded-2xl p-8 md:p-12 mb-8">
                    <h2 className="text-2xl md:text-3xl font-bold mb-3">Create Your Own Coloring Pages</h2>
                    <p className="text-purple-100 mb-6 max-w-xl mx-auto">
                        Use our free AI-powered generator to turn any image into a connect the dots coloring page.
                        Perfect for personalized activities and gifts!
                    </p>
                    <Link
                        href="/"
                        className="inline-block px-8 py-4 bg-white text-purple-600 font-bold rounded-full hover:bg-yellow-400 hover:text-gray-900 transition transform hover:scale-105 shadow-lg"
                    >
                        Try the Free Generator
                    </Link>
                </section>
            </div>
        </main>
    );
}
